### ISSUE TITLE
landscape orientation on iPad

### ISSUE THREAD

**Issue by andrewstephenson-v1** [ajerez/AJNotificationView#8]
the demo project when run in landscape mode causes the notification view to not display correctly.. it flies from right to left and goes off screen

**Comment by ajerez** [comment]
Hi, I can't trigger the bug you are explaining.
Can you give me more data?
Thanks

**Comment by jackysze** [comment]
Hi, the library does not handle screen rotation properly. You may replicate the issue easily by creating a demo application that supports multiple orientations and do the following steps.
1. start the application in portrait mode
2. rotate the application to landscape
3. show AJNotificationView in UIWindow

You will see the notification view flies from left to right. I've looked into the code and seems there are problems in calculating offsets in different orientations.

**Comment by ajerez** [comment]
Sorry for taking so long to fix this issue but lately I don't have much time for working in my repos.

The problem was that in landscape orientation height and width are swapped, because the status bar frame is in the screen's coordinate space.
When this occurs the height of the status bar is 1024 and the notification not display correctly.
This problem is fixed in the last commit

**Comment by sjmn** [comment]
still happening (or happening again in iOS 7.1??)
